name: build and test
on: [push]
jobs:
    pull_code:
        runs-on: ubuntu-latest
        steps: 
            - name: show folder content before checkout
              run: ls -l
            - uses: actions/checkout@v4
              name: "Git Checkout"
            - name: show folder content after checkout
              run: ls -l
            - name: build
              run: dotnet build
    
    # build:
    #     runs-on: ubuntu-latest
    #     needs: pull_code
    #     steps: 
    #         - name: build
    #           run:  |
    #                 dotnet build
