name: build and test
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps: 
            - name: show folder content before checkout
              run: ls -l
            - uses: actions/checkout@v4
              name: "Git Checkout"
            - name: show folder content after checkout
              run: ls -l
            - name: build
              run: dotnet build
    
    test:
        runs-on: ubuntu-latest
        needs: [build]
        steps: 
            - uses: actions/checkout@v4
              name: "Git Checkout"
            - name: test
              run: dotnet test

