name: dependent jobs
on: [push]
jobs:
    fake_build:
        runs-on: ubuntu-latest
        steps:
            - run:  |
                    echo "Fake Build"
                    sleep 10
              name: "Fake Build"
    
    fake_test:
        runs-on: ubuntu-latest
        needs:  fake_build
        steps:
            - run:  |
                    echo "Fake dependent test"
                    sleep 10
              name: "Fake dependent test"
    