name: first test
on: [workflow_dispatch, push, pull_request, issues]
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - run:  echo "Hello World"
              name: "Hello World"
    second_job:
        runs-on: ubuntu-latest
        steps:
            - run:  curl -s https://www.google.com
              name: "Curl Google"
    third_job:
        runs-on: ubuntu-latest
        steps:
            - run:  exit -1
              name: "Error Code Exit"