name: logic output
on: [push]
jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - run:  |
             echo "Hello World"
        name: Hello World

  hellow_world:
    runs-on: ubuntu-latest
    steps:
      - name: show logic output
        run:  |
              echo ${{1}}
              echo ${{null}}
              echo "is 4=3 ${{4==3}}"
              echo "is 4!=3 ${{4!=3}}"
              echo "is 4>3 ${{4>3}}"
              echo "is 3>4 ${{3>4}}"
              name: Logic output