name: logic output
on:
   push:
      paths:
        - "**logic_output.yaml**"
   workflow_dispatch:
   issues:

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - run:  |
             echo "Hello World"
        name: Hello World

  hello_world_logic:
    runs-on: ubuntu-latest
    steps:
      - name: show logic output
        run:  |
              echo ${{1}}
              echo ${{null}}
              echo "is 4=3 ${{4==3}}"
              echo "is 4!=3 ${{4!=3}}"
              echo "is 4>3 ${{4>3}}"
              echo "is 3>4 ${{3>4}}"        
    
  hello_world_conditional:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: "Git Checkout"
      - name: show logic output
        run:  |
            dotnet build
    if: ${{github.event_name =='push'}}

  conditional_test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
          name: "Git Checkout"
        - name: show logic output
          run:  |
              dotnet build
      if: ${{github.event_name =='issues'}}
  