name: multirun
on: [push]
jobs:
    build_and_test:
        strategy:
            matrix: 
                os: [ubuntu-latest, windows-latest]
                node_version: [14,16,18]
        runs-on: ${{matrix.os}}
        defaults:
            run: 
                shell: bash
        steps: 
            - name: show folder content before checkout
              run: ls -l
            - uses: actions/checkout@v4
              name: "Git Checkout"
            - name: show folder content after checkout
              run: ls -l
            - name: build
              run: dotnet build
            - name: test
              run: dotnet test
              continue-on-error: true
    