name: multirun
on: [push]
jobs:
    build_and_test:
        strategy:
            matrix: 
                os: [ubuntu-latest, winows-latest]
        runs-on: ${{matrix.os}}        
        steps: 
            - name: show folder content before checkout
              run: ls -l
            - uses: actions/checkout@v4
              name: "Git Checkout"
            - name: show folder content after checkout
              run: ls -l
            - name: build
              run: dotnet build
    