name: nodebuild
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps: 
            - name: show folder content before checkout
              run: ls -l
            - uses: actions/checkout@v4
              name: "Git Checkout"
            - name: show folder content after checkout
              run: ls -l
            - name: pull modules
              run: |
                    cd nodejs
                    npm install