name: nodebuild
on: [push, workflow_dispatch]
jobs:
    build:
        runs-on: ubuntu-latest
        steps: 
            - name: show folder content before checkout
              run: ls -l
            - uses: actions/checkout@v4
              name: "Git Checkout"
            - name: use Cache for node packages
              uses: actions/cache@v4
              with: 
                path: nodejs/node_modules
                key:  our_modules
              id:  cache_modules
            - name: show folder content after checkout
              run: ls -l
            - name: pull modules
              run: |
                    cd nodejs
                    npm install
            - name: check_cache
              run: echo "Cache hit {{steps.cache_modules.outputs}}"
