name: report on failure
on: [workflow_dispatch]
jobs:
    fake_build:
        runs-on: ubuntu-latest
        steps:
            - run:  |
                    echo "Fake Build"
                    sleep 4
                    exit 0
              name: "Fake Build"
        
    fake_test:
        runs-on: ubuntu-latest
        needs:  fake_build
        steps:
            - run:  |
                    echo "Fake dependent test"
                    sleep 4
              name: "Fake dependent test"
              
    report_failure:
        runs-on: ubuntu-latest
        needs:  fake_build
        if: failure()
        steps:
            - run:  |
                    echo "Report on Failure"
                    sleep 4
              name: "Report on Failure"
    
    report_on_success:
        runs-on: ubuntu-latest
        needs:  fake_build
        if: success()
        steps:
            - run:  |
                    echo "Report on Success"
                    sleep 4
              name: "Report on Success"

    report_to_team:
        runs-on: ubuntu-latest
        needs:  fake_build
        if: always()
        steps:
            - run:  |
                    echo "Report to teams"                    
              name: "Report to teams"