name: using vars 2
on: [push]
jobs:
    show_vars_prod:
        runs-on: ubuntu-latest
        environment: production
        needs: shows_vars_dev
        steps:
            - run:  |
                    echo ${{vars.NEW_ENV_VAR}} 

    show_vars_dev:
        runs-on: ubuntu-latest
        environment: development
        steps:
            - run:  |
                    echo ${{vars.NEW_ENV_VAR}}                                            